### PR TITLE
Fixed the timer/iodevice race between iodevice free and epoll arming the device

### LINKED ISSUE #73: IOMgr Timer cancel race condition
We run into the asan use-after-free issue as reported in the dependent package build
https://github.com/eBay/HomeStore/actions/runs/7715360615/job/21029741703?pr=293

It happens when timer is cancelled, which results in its IODevice being freed (Timer fd = one variant of IODevice). Then IODevice is armed after that resulting in use-after-free.

### PR DESCRIPTION
**Pull request by hkadayam**
IOManager tests are passed

### CODE REVIEW

File: src/lib/epoll/reactor_epoll.hpp [hunk 1]
```diff
@@ -41,9 +41,11 @@ class IOReactorEPoll : public IOReactor {
...
-    std::atomic< bool > m_msg_handler_on;           // Is Message handling ongoing now
-    int m_epollfd = -1;                             // Parent epoll context for this thread
-    io_device_ptr m_msg_iodev;                      // iodev for the messages
-    folly::UMPSCQueue< iomgr_msg*, false > m_msg_q; // Q of message for this thread
+    std::atomic< bool > m_msg_handler_on;                                 // Is Message handling ongoing now
+    int m_epollfd = -1;                                                   // Parent epoll context for this thread
+    io_device_ptr m_msg_iodev;                                            // iodev for the messages
+    folly::UMPSCQueue< iomgr_msg*, false > m_msg_q;                       // Q of message for this thread
+    std::unordered_map< IODevice*, shared< IODevice > > m_removed_iodevs; // Pending IODevices to be removed from epoll
+    bool m_event_processing_phase{false};                                 // Are epoll events are being processed now
```
Comment (sanebay) [inline src/lib/epoll/reactor_epoll.hpp:49]: atomic<bool> not needed ?

Comment (hkadayam) [reply src/lib/epoll/reactor_epoll.hpp:49]: All structures in reactor runs within the thread. So no need of atomic.

**Review by sanebay — APPROVED** [review]
LGTM
